[CBRD-24563]revised answer refer to library change
CUBRID/cubrid-testcases pull request #1363
Opened 2023-01-10 01:08 UTC by tw-kang

http://jira.cubrid.org/browse/CBRD-24563

2023-01-10 04:56 UTC, hgryoo requested changes
Since we are still supporting the cppstd, the existing regression tests should not be erased. In the 'specification changes' section in JIRA, I wrote that 'It is necessary to copy the existing regression tests for the new library backend RE2 and modify the answers if required.'.

2023-01-10 05:00 UTC, hgryoo commented
To avoid regression failures in sql CI, It is enough to set the 'regexp_engine' system parameters need be set to 'cppstd'. Then new test cases for the re2 library need to be added.

2023-01-10 09:21 UTC, tw-kang commented on sql/_32_damson/cbrd_22783_REGEXP_functions/answers/REGEXP_COUNT_unicode.answer
> +0
@hgryoo 
The execution result seems 'regexp_engine' parameter is not set as 'cppstd'. The result is same as 're2'.

2023-01-12 05:48 UTC, hgryoo approved these changes

2023-01-12 05:57 UTC, ssihil approved these changes

2023-01-12 06:00 UTC, merged