[CBRD-24478] add new cases for Make sure that the index is not skewed by duplicate keys.
CUBRID/cubrid-testcases pull request #1527
Opened 2023-08-01 08:16 UTC by hiclass

http://jira.cubrid.org/browse/CBRD-24478

2023-08-02 11:41 UTC, tw-kang requested changes
To maintain the independency of every test case please add 'drop table if exsists' phrase in every sql cases.

2023-08-02 11:41 UTC, tw-kang commented on sql/_34_fig/cbrd_24478/deduplicate/cases/01_create_table.sql
> +
```suggestion

DROP TABLE IF EXISTS [t_parent];
DROP TABLE IF EXISTS [t_parent2];

```

2023-08-02 11:41 UTC, tw-kang commented on sql/_34_fig/cbrd_24478/deduplicate/cases/02_create_table_fk.sql
> +
```suggestion

DROP TABLE IF EXISTS [t_child];
DROP TABLE IF EXISTS [t_parent];

```

2023-08-02 11:41 UTC, tw-kang commented on sql/_34_fig/cbrd_24478/deduplicate/cases/03_create_indexes.sql
> +
```suggestion

DROP TABLE IF EXISTS [t_child];

```

2023-08-02 11:41 UTC, tw-kang commented on sql/_34_fig/cbrd_24478/deduplicate/cases/04_partition_with_type_change.sql
> +-- Modify column with compatible type change on single column index and deduplicate option
```suggestion
-- Modify column with compatible type change on single column index and deduplicate option
drop table if exists tbl;

```

2023-08-03 02:26 UTC, tw-kang commented
Refer to CTP guide CREATE TABLE should be preceded by DROP TABLE if exists.
Including 'if exists' does not cause an error.
[CTP guide](https://github.com/CUBRID/cubrid-testtools/blob/develop/doc/sql_guide.md#6-test-case-specification)

2023-08-08 00:03 UTC, ctshim approved these changes

2023-08-08 01:31 UTC, hiclass commented on sql/_34_fig/cbrd_24478/deduplicate/cases/01_create_table.sql
> +
It would not need

2023-08-08 01:32 UTC, hiclass commented on sql/_34_fig/cbrd_24478/deduplicate/cases/02_create_table_fk.sql
> +
It would not need

2023-08-08 01:32 UTC, hiclass commented on sql/_34_fig/cbrd_24478/deduplicate/cases/03_create_indexes.sql
> +
It would not need

2023-08-08 01:32 UTC, hiclass commented on sql/_34_fig/cbrd_24478/deduplicate/cases/04_partition_with_type_change.sql
> +-- Modify column with compatible type change on single column index and deduplicate option
It would not need

2023-08-08 05:43 UTC, tw-kang commented on sql/_34_fig/cbrd_24478/deduplicate/cases/02_create_table_fk.sql
> +ALTER TABLE DROP CONSTRAINT [fk_t_child_parent_pid] FOREIGN KEY ([pid]);
is this error case?

2023-08-08 05:43 UTC, tw-kang commented on sql/_34_fig/cbrd_24478/deduplicate/answers/02_create_table_fk.answer
> +Error:-493
is this error case?

2023-08-18 12:19 UTC, tw-kang reviewed
CTP application cannot run next query if the comment is written at the end of the same line.

2023-08-18 12:19 UTC, tw-kang commented on sql/_34_fig/cbrd_24478/deduplicate/cases/03_alter_table.sql
> +ALTER TABLE [t_parent] ADD CONSTRAINT PRIMARY KEY([id]); -- Fail
```suggestion
-- error case
ALTER TABLE [t_parent] ADD CONSTRAINT PRIMARY KEY([id]);
```

2023-08-21 08:29 UTC, tw-kang approved these changes

2023-08-24 07:56 UTC, tw-kang approved these changes

2023-08-29 04:29 UTC, ssihil approved these changes

2023-09-15 07:36 UTC, kwonhoil approved these changes

2023-09-21 06:23 UTC, merged