CBRD-25176
CUBRID/cubrid-testcases pull request #1844
Opened 2024-08-27 08:56 UTC by kiho-um

Refer to http://jira.cubrid.org/browse/CBRD-25176

2024-08-28 01:08 UTC, kwonhoil commented on sql/_13_issues/_24_1h/cases/cbrd_25176.sql
> +
아래 쿼리를 추가하는 것이 좋을것 같습니다.

alter table b_child add constraint fk_id_name2 FOREIGN KEY(id,name) REFERENCES a_parent(id,name);
alter table b_child  drop constraint fk_id_name2;

2024-08-28 01:09 UTC, kwonhoil commented on sql/_13_issues/_24_1h/cases/cbrd_25176.sql
> +
첫줄에 이슈내용 설명 추가해 주세요.

There are cases where problems arise when deduplicate indexes are created with FK.

2024-08-28 04:38 UTC, ssihil commented
타이틀 형식을 맞춰주세요. Pull Request의 제목에는 항상 관련된 JIRA 이슈 번호를 기입해야 합니다.
'[CBRD-25176] Add sql testcase for issue summary'

그리고 'sql/_13_issues/\_**24_2h**' 하위에 생성되어야 합니다.

2024-08-28 04:38 UTC, ssihil commented on sql/_13_issues/_24_1h/cases/cbrd_25176.sql
> +set system parameters 'print_index_detail=yes';
show create table 구문이 사용되지 않으므로 불필요합니다.

2024-08-28 04:39 UTC, ssihil commented on sql/_13_issues/_24_1h/cases/cbrd_25176.sql
> +set system parameters 'print_index_detail=yes';
show create table 구문이 사용되지 않으므로 불필요합니다.

2024-08-28 06:25 UTC, kiho-um commented on sql/_13_issues/_24_1h/cases/cbrd_25176.sql
> +set system parameters 'print_index_detail=yes';
타이틀 형식을 맞춰주세요. Pull Request의 제목에는 항상 관련된 JIRA 이슈 번호를 기입해야 합니다.
'[CBRD-25176] Add sql testcase for issue summary'
 -> 타이틀 기입이 빠졌네요. 기입 하겠습니다.

그리고 'sql/_13_issues/_24_2h' 하위에 생성되어야 합니다.
 -> http://jira.cubrid.org/browse/CBRD-25176에 생성일자(Created) 가 2024-01-23 이라서  sql/_13_issues/_24_1h에 생성하였습니다. 제가 알고 있는 작성 기준으로 다른 건지요.

'print_index_detail=yes'는 show create table 구문이 사용되지 않으므로 불필요합니다.
삭제 처리 하겠습니다.

2024-08-28 07:41 UTC, ssihil commented on sql/_13_issues/_24_1h/cases/cbrd_25176.sql
> +set system parameters 'print_index_detail=yes';
TC 경로는 TC 작성일 기준으로 합니다. 경우에 따라서는 이슈가 수 년전 생성된 것을 작성할 수도 있기 때문입니다.

2024-08-29 04:11 UTC, kiho-um commented on sql/_13_issues/_24_1h/cases/cbrd_25176.sql
> +
alter table b_child add constraint fk_id_name1 FOREIGN KEY(id,name) with deduplicate=13 REFERENCES a_parent(id,name);
쿼리문에 위 외래키를 생성 했기 때문에 추가할 필요가 없을 것 같습니다.
같은 자식 테이블(b_child)의 컬럼이 부모 테이블의 같은 컬럼으로 이름만 다르게 생성할 경우 인덱스가 이미 존재한다는 메시지가 나옵니다.

2024-08-29 04:48 UTC, kiho-um commented on sql/_13_issues/_24_1h/cases/cbrd_25176.sql
> +set system parameters 'print_index_detail=yes';
TC 경로 변경 및 set system parameters 'print_index_detail=yes';  삭제 하였습니다.

2024-08-29 04:49 UTC, kiho-um commented on sql/_13_issues/_24_1h/cases/cbrd_25176.sql
> +
alter table b_child drop constraint fk_id_name1;
cases, answers 쿼리문, 답지 추가

2024-08-29 04:52 UTC, kiho-um commented on sql/_13_issues/_24_1h/cases/cbrd_25176.sql
> +
Title  추가
"Failure when creating fk of deduplicate attribute after applying"

2024-09-03 00:45 UTC, kiho-um commented on sql/_13_issues/_24_1h/cases/cbrd_25176.sql
> +
첫줄에 TC에 대한 내용 추가 했습니다.
--There are cases where problems arise when deduplicate indexes are created with FK.

2024-09-03 01:16 UTC, ssihil approved these changes

2024-09-03 05:35 UTC, bagus-kim commented on sql/_13_issues/_24_2h/cases/cbrd_25176.sql
> +
;get deduplicate_key_level 으로 0이 되었는지 확인이 필요하지 않을까요?

2024-09-03 07:36 UTC, kiho-um commented on sql/_13_issues/_24_2h/cases/cbrd_25176.sql
> +
확인 하기 위해서는 명령어(CTP는 java기반)로 답지(answer)를 만들어야 하지만, 
get으로 특정 parameter를 가져올 수 없어서 답지(answer)를 만들 수가 없습니다.
그러므로 set system parameter가 되었다는 전제하에 next query문을 수행하도록 했습니다.

2024-09-03 23:56 UTC, bagus-kim approved these changes

2024-09-09 06:20 UTC, tw-kang requested changes

2024-09-09 06:20 UTC, tw-kang commented on sql/_13_issues/_24_2h/cases/cbrd_25176.sql
> +drop table a_parent;
```suggestion
drop table a_parent;
set system parameters 'deduplicate_key_level=default';
```
명시적으로 default 설정을 추가하여 다른 케이스 수행 시 default 로 동작하는것을 보장합니다.

2024-09-09 07:26 UTC, ctshim approved these changes

2024-09-09 08:10 UTC, kiho-um commented on sql/_13_issues/_24_2h/cases/cbrd_25176.sql
> +drop table a_parent;
parameter 기본값 적용하였습니다.
set system parameters 'deduplicate_key_level=-1';

2024-09-12 09:01 UTC, merged