[CBRD-23916] New cases for the spec change of truncate
CUBRID/cubrid-testcases pull request #980
Opened 2021-08-09 08:55 UTC by sjkim777

http://jira.cubrid.org/browse/CBRD-23916

2021-08-12 01:58 UTC, wrlawodms requested changes
`sql/_33_elderberry/cbrd_23916/answers/spec_04.answer` has some problem. It prints errors even if the basic `CREATE TABLE` statement and has different results from my test. Please check it again and let me know!

2021-08-12 03:58 UTC, wrlawodms approved these changes

2021-08-12 05:22 UTC, ssihil approved these changes

2021-08-13 05:16 UTC, sy052 approved these changes

2021-08-26 09:56 UTC, merged